In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
train = pd.read_csv("train.csv")

In [6]:
train

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
5,19,0,5,1,4,0,0,0,0,0,...,4,2,0,9,0,1,0,1,1,1
6,20,0,2,1,3,1,0,0,1,0,...,3,0,0,10,0,1,0,0,1,0
7,22,0,5,1,4,0,0,1,0,0,...,7,1,3,6,1,0,1,0,1,0
8,26,0,5,1,3,1,0,0,0,1,...,4,2,1,5,0,1,0,0,0,1
9,28,1,1,1,2,0,0,0,1,0,...,3,5,0,6,0,1,0,0,1,0
10,34,0,5,2,2,0,0,0,0,1,...,6,3,3,6,0,1,1,0,1,1
11,35,0,2,1,3,1,0,0,1,0,...,9,2,1,10,0,1,0,1,0,0
12,36,0,2,1,1,1,0,0,0,1,...,6,3,3,8,0,0,1,0,0,1
13,43,0,1,1,3,1,0,0,1,0,...,2,0,4,3,0,0,1,0,1,0
14,46,0,5,1,11,0,0,0,0,0,...,4,1,3,9,0,0,0,0,1,0
15,48,0,5,1,3,1,0,0,1,0,...,5,2,6,7,0,1,1,0,1,0
16,50,0,1,2,1,0,0,0,0,1,...,3,3,1,8,0,0,1,0,0,0
17,58,0,5,1,6,0,1,1,0,0,...,9,1,3,9,0,1,1,0,0,0
18,61,0,5,1,8,0,0,1,0,0,...,3,1,6,5,0,0,0,1,0,0
19,64,1,0,1,2,1,0,1,0,0,...,10,3,1,11,0,1,1,0,1,0
20,65,0,0,1,2,0,0,1,0,0,...,7,2,2,4,0,1,0,0,1,0
21,66,0,0,1,5,1,4,1,0,0,...,5,5,3,8,0,0,0,0,1,0
22,72,0,5,3,6,1,3,0,1,0,...,8,1,3,5,0,0,0,0,0,1
23,74,0,2,1,2,1,0,0,1,0,...,7,1,3,9,0,1,0,1,0,0
24,77,0,0,1,2,0,0,1,0,0,...,5,1,2,8,0,1,1,1,0,0
25,78,0,0,1,7,0,0,1,0,0,...,6,4,4,4,0,0,1,1,0,1
26,79,0,0,1,4,1,0,0,0,1,...,4,2,4,3,0,1,1,1,0,1
27,80,0,4,1,6,0,0,0,0,0,...,7,2,2,11,0,1,0,1,0,0
28,84,1,0,2,0,1,4,1,0,0,...,3,2,0,8,0,1,1,0,0,0
29,85,0,3,2,2,0,0,1,0,0,...,2,0,4,7,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595182,1487945,0,0,1,2,0,0,1,0,0,...,12,0,5,8,0,0,0,1,1,0
595183,1487951,0,1,1,9,0,0,1,0,0,...,2,2,3,7,0,1,1,0,1,0
595184,1487952,0,1,1,5,0,0,1,0,0,...,7,0,3,9,0,0,0,0,0,1
595185,1487954,0,0,2,8,1,0,0,0,1,...,10,1,1,11,0,1,0,1,0,0
595186,1487957,0,0,1,3,1,0,0,1,0,...,10,0,2,9,0,0,1,1,0,0
595187,1487958,0,0,1,7,0,4,0,0,0,...,5,1,4,9,0,1,1,0,0,1
595188,1487962,0,2,1,3,0,0,1,0,0,...,8,1,6,6,0,1,1,0,0,0
595189,1487963,0,3,1,9,0,0,1,0,0,...,7,0,8,4,0,1,0,1,1,0
595190,1487964,0,1,2,3,0,0,1,0,0,...,1,0,4,6,0,0,1,0,0,0
595191,1487968,0,5,1,3,0,0,0,0,1,...,8,2,1,11,0,0,1,1,0,1
595192,1487973,0,0,1,1,0,0,0,1,0,...,5,1,5,5,0,1,1,0,1,1
595193,1487975,0,0,2,0,0,-1,0,1,0,...,6,1,3,5,0,1,0,1,0,0
595194,1487976,0,0,1,7,1,0,0,1,0,...,6,1,4,12,0,1,1,0,0,0
595195,1487980,0,0,3,3,1,0,0,1,0,...,8,0,2,5,0,1,0,0,1,1
595196,1487983,0,1,1,2,0,0,1,0,0,...,6,0,1,11,1,1,0,0,1,1
595197,1487988,0,1,1,7,1,0,0,1,0,...,4,1,3,6,0,0,1,1,1,0
595198,1487990,0,5,1,7,1,0,0,0,0,...,6,2,2,14,0,1,1,0,0,0
595199,1487992,0,3,1,3,1,0,0,0,1,...,1,1,1,10,0,0,1,0,1,0
595200,1487994,0,1,1,1,0,3,1,0,0,...,2,3,3,12,0,0,1,0,0,0
595201,1487996,0,0,2,2,1,0,0,0,0,...,4,1,2,6,1,1,0,1,1,0
595202,1488001,0,4,1,3,0,0,0,1,0,...,11,6,2,6,0,1,1,0,1,0
595203,1488005,0,3,2,3,1,0,0,1,0,...,5,2,1,6,0,0,0,0,0,0
595204,1488008,0,1,2,2,1,0,0,1,0,...,3,1,3,9,0,1,0,0,1,0
595205,1488009,0,0,3,6,1,0,0,1,0,...,7,1,2,6,1,0,1,0,0,0
595206,1488011,0,0,1,2,0,0,0,0,0,...,8,0,1,7,0,1,1,0,0,0
595207,1488013,0,3,1,10,0,0,0,0,0,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,...,4,4,3,8,0,1,0,0,0,0

In [7]:
train.describe()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,5.952120e+05,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,...,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,7.438036e+05,0.036448,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,...,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,4.293678e+05,0.187401,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,...,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,7.000000e+00,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.719915e+05,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.435475e+05,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,1.115549e+06,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.488027e+06,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
train.columns.values

array(['id', 'target', 'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03',
       'ps_ind_04_cat', 'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin',
       'ps_ind_08_bin', 'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin',
       'ps_ind_12_bin', 'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15',
       'ps_ind_16_bin', 'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01',
       'ps_reg_02', 'ps_reg_03', 'ps_car_01_cat', 'ps_car_02_cat',
       'ps_car_03_cat', 'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat',
       'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat', 'ps_car_10_cat',
       'ps_car_11_cat', 'ps_car_11', 'ps_car_12', 'ps_car_13', 'ps_car_14',
       'ps_car_15', 'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04',
       'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08',
       'ps_calc_09', 'ps_calc_10', 'ps_calc_11', 'ps_calc_12',
       'ps_calc_13', 'ps_calc_14', 'ps_calc_15_bin', 'ps_calc_16_bin',
       'ps_calc_17_bin', 'ps_calc_18_bin', 'ps_calc_19_bin',
       'ps_calc_20_bin'], dtype=object)

In [10]:
header = train.columns.values

In [12]:
for att in header:
    print(train[att].describe())
    print('\n')

count    5.952120e+05
mean     7.438036e+05
std      4.293678e+05
min      7.000000e+00
25%      3.719915e+05
50%      7.435475e+05
75%      1.115549e+06
max      1.488027e+06
Name: id, dtype: float64


count    595212.000000
mean          0.036448
std           0.187401
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: target, dtype: float64


count    595212.000000
mean          1.900378
std           1.983789
min           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
max           7.000000
Name: ps_ind_01, dtype: float64


count    595212.000000
mean          1.358943
std           0.664594
min          -1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           4.000000
Name: ps_ind_02_cat, dtype: float64


count    595212.000000
mean          4.423318
std           2.699902
min           0.000000
25%           2.000000
50%           4.000000
75%           6.000000
max          11.000000
Name: ps_ind_03, dtype: float64


count    595212.000000
mean          0.416794
std           0.493311
min          -1.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_ind_04_cat, dtype: float64


count    595212.000000
mean          0.405188
std           1.350642
min          -1.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           6.000000
Name: ps_ind_05_cat, dtype: float64


count    595212.000000
mean          0.393742
std           0.488579
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_ind_06_bin, dtype: float64


count    595212.000000
mean          0.257033
std           0.436998
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_ind_07_bin, dtype: float64


count    595212.000000
mean          0.163921
std           0.370205
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_08_bin, dtype: float64


count    595212.000000
mean          0.185304
std           0.388544
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_09_bin, dtype: float64


count    595212.000000
mean          0.000373
std           0.019309
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_10_bin, dtype: float64


count    595212.000000
mean          0.001692
std           0.041097
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_11_bin, dtype: float64


count    595212.000000
mean          0.009439
std           0.096693
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_12_bin, dtype: float64


count    595212.000000
mean          0.000948
std           0.030768
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_13_bin, dtype: float64


count    595212.000000
mean          0.012451
std           0.127545
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           4.000000
Name: ps_ind_14, dtype: float64


count    595212.000000
mean          7.299922
std           3.546042
min           0.000000
25%           5.000000
50%           7.000000
75%          10.000000
max          13.000000
Name: ps_ind_15, dtype: float64


count    595212.000000
mean          0.660823
std           0.473430
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_ind_16_bin, dtype: float64


count    595212.000000
mean          0.121081
std           0.326222
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_17_bin, dtype: float64


count    595212.000000
mean          0.153446
std           0.360417
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_18_bin, dtype: float64


count    595212.000000
mean          0.610991
std           0.287643
min           0.000000
25%           0.400000
50%           0.700000
75%           0.900000
max           0.900000
Name: ps_reg_01, dtype: float64


count    595212.000000
mean          0.439184
std           0.404264
min           0.000000
25%           0.200000
50%           0.300000
75%           0.600000
max           1.800000
Name: ps_reg_02, dtype: float64


count    595212.000000
mean          0.551102
std           0.793506
min          -1.000000
25%           0.525000
50%           0.720677
75%           1.000000
max           4.037945
Name: ps_reg_03, dtype: float64


count    595212.000000
mean          8.295933
std           2.508270
min          -1.000000
25%           7.000000
50%           7.000000
75%          11.000000
max          11.000000
Name: ps_car_01_cat, dtype: float64


count    595212.000000
mean          0.829931
std           0.375716
min          -1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_car_02_cat, dtype: float64


count    595212.000000
mean         -0.504899
std           0.788654
min          -1.000000
25%          -1.000000
50%          -1.000000
75%           0.000000
max           1.000000
Name: ps_car_03_cat, dtype: float64


count    595212.000000
mean          0.725192
std           2.153463
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           9.000000
Name: ps_car_04_cat, dtype: float64


count    595212.000000
mean         -0.157732
std           0.844417
min          -1.000000
25%          -1.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_car_05_cat, dtype: float64


count    595212.000000
mean          6.555340
std           5.501445
min           0.000000
25%           1.000000
50%           7.000000
75%          11.000000
max          17.000000
Name: ps_car_06_cat, dtype: float64


count    595212.000000
mean          0.910027
std           0.347106
min          -1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_car_07_cat, dtype: float64


count    595212.000000
mean          0.832080
std           0.373796
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_car_08_cat, dtype: float64


count    595212.000000
mean          1.328890
std           0.978747
min          -1.000000
25%           0.000000
50%           2.000000
75%           2.000000
max           4.000000
Name: ps_car_09_cat, dtype: float64


count    595212.000000
mean          0.992136
std           0.091619
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           2.000000
Name: ps_car_10_cat, dtype: float64


count    595212.000000
mean         62.215674
std          33.012455
min           1.000000
25%          32.000000
50%          65.000000
75%          93.000000
max         104.000000
Name: ps_car_11_cat, dtype: float64


count    595212.000000
mean          2.346072
std           0.832548
min          -1.000000
25%           2.000000
50%           3.000000
75%           3.000000
max           3.000000
Name: ps_car_11, dtype: float64


count    595212.000000
mean          0.379945
std           0.058327
min          -1.000000
25%           0.316228
50%           0.374166
75%           0.400000
max           1.264911
Name: ps_car_12, dtype: float64


count    595212.000000
mean          0.813265
std           0.224588
min           0.250619
25%           0.670867
50%           0.765811
75%           0.906190
max           3.720626
Name: ps_car_13, dtype: float64


count    595212.000000
mean          0.276256
std           0.357154
min          -1.000000
25%           0.333167
50%           0.368782
75%           0.396485
max           0.636396
Name: ps_car_14, dtype: float64


count    595212.000000
mean          3.065899
std           0.731366
min           0.000000
25%           2.828427
50%           3.316625
75%           3.605551
max           3.741657
Name: ps_car_15, dtype: float64


count    595212.000000
mean          0.449756
std           0.287198
min           0.000000
25%           0.200000
50%           0.500000
75%           0.700000
max           0.900000
Name: ps_calc_01, dtype: float64


count    595212.000000
mean          0.449589
std           0.286893
min           0.000000
25%           0.200000
50%           0.400000
75%           0.700000
max           0.900000
Name: ps_calc_02, dtype: float64

count    595212.000000
mean          0.449849
std           0.287153
min           0.000000
25%           0.200000
50%           0.500000
75%           0.700000
max           0.900000
Name: ps_calc_03, dtype: float64


count    595212.000000
mean          2.372081
std           1.117219
min           0.000000
25%           2.000000
50%           2.000000
75%           3.000000
max           5.000000
Name: ps_calc_04, dtype: float64


count    595212.000000
mean          1.885886
std           1.134927
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           6.000000
Name: ps_calc_05, dtype: float64


count    595212.000000
mean          7.689445
std           1.334312
min           0.000000
25%           7.000000
50%           8.000000
75%           9.000000
max          10.000000
Name: ps_calc_06, dtype: float64


count    595212.000000
mean          3.005823
std           1.414564
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           9.000000
Name: ps_calc_07, dtype: float64


count    595212.000000
mean          9.225904
std           1.459672
min           2.000000
25%           8.000000
50%           9.000000
75%          10.000000
max          12.000000
Name: ps_calc_08, dtype: float64


count    595212.000000
mean          2.339034
std           1.246949
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           7.000000
Name: ps_calc_09, dtype: float64


count    595212.000000
mean          8.433590
std           2.904597
min           0.000000
25%           6.000000
50%           8.000000
75%          10.000000
max          25.000000
Name: ps_calc_10, dtype: float64


count    595212.000000
mean          5.441382
std           2.332871
min           0.000000
25%           4.000000
50%           5.000000
75%           7.000000
max          19.000000
Name: ps_calc_11, dtype: float64


count    595212.000000
mean          1.441918
std           1.202963
min           0.000000
25%           1.000000
50%           1.000000
75%           2.000000
max          10.000000
Name: ps_calc_12, dtype: float64


count    595212.000000
mean          2.872288
std           1.694887
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max          13.000000
Name: ps_calc_13, dtype: float64


count    595212.000000
mean          7.539026
std           2.746652
min           0.000000
25%           6.000000
50%           7.000000
75%           9.000000
max          23.000000
Name: ps_calc_14, dtype: float64


count    595212.000000
mean          0.122427
std           0.327779
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_calc_15_bin, dtype: float64


count    595212.000000
mean          0.627840
std           0.483381
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_calc_16_bin, dtype: float64


count    595212.000000
mean          0.554182
std           0.497056
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_calc_17_bin, dtype: float64


count    595212.000000
mean          0.287182
std           0.452447
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_calc_18_bin, dtype: float64


count    595212.000000
mean          0.349024
std           0.476662
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_calc_19_bin, dtype: float64


count    595212.000000
mean          0.153318
std           0.360295
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_calc_20_bin, dtype: float64

In [13]:
test = pd.read_csv("test.csv")

In [14]:
test

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1
5,5,0,1,6,0,0,1,0,0,0,...,8,1,4,9,1,0,1,0,1,0
6,6,0,1,3,0,0,0,1,0,0,...,2,0,4,6,1,1,0,0,0,0
7,8,0,1,0,0,0,1,0,0,0,...,3,1,4,9,0,1,0,0,0,0
8,10,0,1,7,0,0,0,1,0,0,...,5,1,4,6,0,0,1,0,0,0
9,11,1,1,6,0,0,0,0,0,1,...,6,1,6,10,0,1,1,0,0,0
10,12,0,1,5,0,4,1,0,0,0,...,2,1,1,8,0,1,1,1,0,0
11,14,1,1,4,0,0,1,0,0,0,...,4,2,7,8,0,1,0,1,0,0
12,15,1,1,2,1,0,0,1,0,0,...,3,4,0,12,1,1,0,0,1,0
13,18,3,1,3,0,0,0,1,0,0,...,7,0,5,9,0,0,0,1,0,0
14,21,0,2,1,0,6,1,0,0,0,...,6,3,5,6,0,0,1,0,0,0
15,23,2,2,2,0,0,0,0,1,0,...,9,0,2,11,0,0,1,1,0,0
16,24,2,1,3,0,0,0,0,1,0,...,3,1,2,8,0,1,1,0,0,0
17,25,0,2,0,1,-1,1,0,0,0,...,5,2,3,9,1,1,1,0,1,0
18,27,3,2,1,0,0,1,0,0,0,...,4,3,5,9,0,1,1,0,1,0
19,29,1,1,4,1,6,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
20,30,0,1,4,0,0,1,0,0,0,...,3,1,4,6,1,1,0,1,0,0
21,31,6,2,1,0,0,0,0,0,1,...,4,2,4,7,0,1,0,0,1,0
22,32,0,1,8,0,0,0,1,0,0,...,2,0,4,10,0,0,1,1,0,0
23,33,1,1,2,0,0,1,0,0,0,...,9,0,6,7,1,1,0,1,0,0
24,37,5,2,6,1,0,0,0,0,1,...,9,2,4,5,0,1,0,1,0,0
25,38,1,2,0,1,0,0,1,0,0,...,7,3,2,6,0,1,1,1,0,0
26,39,5,2,2,1,0,0,0,1,0,...,3,0,7,8,0,1,0,1,0,1
27,40,1,1,3,0,0,1,0,0,0,...,6,3,2,8,0,0,1,1,0,0
28,41,0,1,1,1,0,0,1,0,0,...,7,2,4,5,0,1,1,0,1,0
29,42,1,2,7,1,0,1,0,0,0,...,4,2,2,4,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892786,1487982,2,1,3,0,0,1,0,0,0,...,8,0,1,8,0,1,1,0,1,1
892787,1487984,1,1,2,1,0,1,0,0,0,...,9,0,2,4,0,1,1,0,1,0
892788,1487985,3,1,3,0,0,0,0,1,0,...,14,2,3,6,1,1,1,0,1,1
892789,1487986,1,2,1,1,0,0,0,0,1,...,5,0,1,7,1,0,0,0,1,0
892790,1487987,0,3,5,1,0,0,0,1,0,...,10,2,2,5,0,1,1,0,0,1
892791,1487989,1,1,8,0,0,1,0,0,0,...,7,0,6,4,0,1,0,1,0,1
892792,1487991,1,1,6,0,0,1,0,0,0,...,3,1,3,4,0,0,0,1,0,0
892793,1487993,0,2,1,0,6,1,0,0,0,...,5,2,2,5,0,0,1,0,0,0
892794,1487995,6,2,7,0,0,0,0,0,1,...,10,3,2,6,0,1,1,0,0,0
892795,1487997,2,1,8,0,0,0,0,0,1,...,12,2,3,11,0,1,0,0,1,1
892796,1487998,0,2,1,1,0,0,1,0,0,...,4,1,1,3,0,0,1,0,1,0
892797,1487999,2,1,5,0,6,0,0,1,0,...,9,2,2,13,0,1,0,0,0,0
892798,1488000,7,1,4,0,0,0,0,0,1,...,8,2,2,7,0,0,0,0,0,0
892799,1488002,0,2,0,0,-1,1,0,0,0,...,7,0,4,9,0,1,1,0,0,0
892800,1488003,1,1,2,1,0,0,1,0,0,...,3,1,2,7,0,1,1,0,0,0
892801,1488004,0,1,7,0,0,1,0,0,0,...,7,3,4,7,1,1,0,0,1,0
892802,1488006,2,1,2,1,0,0,1,0,0,...,6,1,3,10,0,1,1,0,1,0
892803,1488007,3,1,2,1,0,1,0,0,0,...,6,1,2,8,0,0,1,1,1,0
892804,1488010,4,1,6,0,0,1,0,0,0,...,5,0,3,10,0,1,1,1,1,0
892805,1488012,5,1,6,0,0,1,0,0,0,...,6,0,0,7,0,0,1,0,0,0
892806,1488014,0,1,6,1,0,1,0,0,0,...,5,2,5,10,0,0,1,1,0,0
892807,1488015,0,1,3,0,0,0,1,0,0,...,4,3,3,6,0,0,0,1,1,0
892808,1488018,1,1,6,0,4,1,0,0,0,...,7,1,2,4,0,0,1,1,1,0
892809,1488019,2,1,7,0,0,0,0,0,1,...,7,4,3,5,0,1,1,0,0,0
892810,1488020,0,1,6,0,0,0,0,0,1,...,2,3,5,7,0,1,1,1,1,1
892811,1488022,0,1,6,0,0,0,1,0,0,...,4,2,3,4,0,1,0,0,1,0
892812,1488023,5,3,5,1,0,0,0,1,0,...,6,2,2,11,0,0,1,1,0,0
892813,1488024,0,1,5,0,0,1,0,0,0,...,5,2,2,11,0,1,1,0,0,0
892814,1488025,6,1,5,1,0,0,0,0,1,...,1,1,2,7,1,1,0,0,0,0
892815,1488026,7,1,4,1,0,0,0,0,1,...,5,2,2,7,0,1,1,1,0,0

In [15]:
header = test.columns.values

In [16]:
header

array(['id', 'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03', 'ps_ind_04_cat',
       'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin', 'ps_ind_08_bin',
       'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin', 'ps_ind_12_bin',
       'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15', 'ps_ind_16_bin',
       'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01', 'ps_reg_02',
       'ps_reg_03', 'ps_car_01_cat', 'ps_car_02_cat', 'ps_car_03_cat',
       'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat', 'ps_car_07_cat',
       'ps_car_08_cat', 'ps_car_09_cat', 'ps_car_10_cat', 'ps_car_11_cat',
       'ps_car_11', 'ps_car_12', 'ps_car_13', 'ps_car_14', 'ps_car_15',
       'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04',
       'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08',
       'ps_calc_09', 'ps_calc_10', 'ps_calc_11', 'ps_calc_12',
       'ps_calc_13', 'ps_calc_14', 'ps_calc_15_bin', 'ps_calc_16_bin',
       'ps_calc_17_bin', 'ps_calc_18_bin', 'ps_calc_19_bin',
       'ps_calc_20_bin'], dtype=object)

In [17]:
for att in header:
    print(test[att].describe())
    print('\n')

count    8.928160e+05
mean     7.441535e+05
std      4.296830e+05
min      0.000000e+00
25%      3.720218e+05
50%      7.443070e+05
75%      1.116308e+06
max      1.488026e+06
Name: id, dtype: float64


count    892816.000000
mean          1.902371
std           1.986503
min           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
max           7.000000
Name: ps_ind_01, dtype: float64


count    892816.000000
mean          1.358613
std           0.663002
min          -1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           4.000000
Name: ps_ind_02_cat, dtype: float64


count    892816.000000
mean          4.413734
std           2.700149
min           0.000000
25%           2.000000
50%           4.000000
75%           6.000000
max          11.000000
Name: ps_ind_03, dtype: float64


count    892816.000000
mean          0.417361
std           0.493453
min          -1.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_ind_04_cat, dtype: float64


count    892816.000000
mean          0.408132
std           1.355068
min          -1.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           6.000000
Name: ps_ind_05_cat, dtype: float64


count    892816.000000
mean          0.393246
std           0.488471
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_ind_06_bin, dtype: float64


count    892816.000000
mean          0.257191
std           0.437086
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_ind_07_bin, dtype: float64


count    892816.000000
mean          0.163659
std           0.369966
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_08_bin, dtype: float64


count    892816.000000
mean          0.185905
std           0.389030
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_09_bin, dtype: float64


count    892816.000000
mean          0.000373
std           0.019309
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_10_bin, dtype: float64


count    892816.000000
mean          0.001595
std           0.039905
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_11_bin, dtype: float64


count    892816.000000
mean          0.009376
std           0.096375
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_12_bin, dtype: float64


count    892816.000000
mean          0.001039
std           0.032223
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_13_bin, dtype: float64


count    892816.000000
mean          0.012383
std           0.127251
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           4.000000
Name: ps_ind_14, dtype: float64


count    892816.000000
mean          7.296862
std           3.541948
min           0.000000
25%           5.000000
50%           7.000000
75%          10.000000
max          13.000000
Name: ps_ind_15, dtype: float64


count    892816.000000
mean          0.660591
std           0.473509
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_ind_16_bin, dtype: float64


count    892816.000000
mean          0.120399
std           0.325428
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_17_bin, dtype: float64


count    892816.000000
mean          0.154973
std           0.361879
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_ind_18_bin, dtype: float64


count    892816.000000
mean          0.611057
std           0.287699
min           0.000000
25%           0.400000
50%           0.700000
75%           0.900000
max           0.900000
Name: ps_reg_01, dtype: float64


count    892816.000000
mean          0.439868
std           0.404678
min           0.000000
25%           0.200000
50%           0.300000
75%           0.600000
max           1.800000
Name: ps_reg_02, dtype: float64


count    892816.000000
mean          0.551740
std           0.794023
min          -1.000000
25%           0.524404
50%           0.721110
75%           1.002185
max           4.423517
Name: ps_reg_03, dtype: float64


count    892816.000000
mean          8.292038
std           2.508331
min          -1.000000
25%           7.000000
50%           7.000000
75%          11.000000
max          11.000000
Name: ps_car_01_cat, dtype: float64


count    892816.00000
mean          0.82994
std           0.37570
min          -1.00000
25%           1.00000
50%           1.00000
75%           1.00000
max           1.00000
Name: ps_car_02_cat, dtype: float64


count    892816.000000
mean         -0.504895
std           0.788753
min          -1.000000
25%          -1.000000
50%          -1.000000
75%           0.000000
max           1.000000
Name: ps_car_03_cat, dtype: float64


count    892816.000000
mean          0.725798
std           2.154886
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           9.000000
Name: ps_car_04_cat, dtype: float64


count    892816.000000
mean         -0.158449
std           0.844566
min          -1.000000
25%          -1.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_car_05_cat, dtype: float64


count    892816.000000
mean          6.564297
std           5.500485
min           0.000000
25%           1.000000
50%           7.000000
75%          11.000000
max          17.000000
Name: ps_car_06_cat, dtype: float64


count    892816.000000
mean          0.910144
std           0.347283
min          -1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_car_07_cat, dtype: float64


count    892816.000000
mean          0.832311
std           0.373590
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_car_08_cat, dtype: float64


count    892816.000000
mean          1.327911
std           0.978741
min          -1.000000
25%           0.000000
50%           2.000000
75%           2.000000
max           4.000000
Name: ps_car_09_cat, dtype: float64


count    892816.000000
mean          0.992134
std           0.091530
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           2.000000
Name: ps_car_10_cat, dtype: float64


count    892816.000000
mean         62.284293
std          33.003714
min           1.000000
25%          32.000000
50%          65.000000
75%          94.000000
max         104.000000
Name: ps_car_11_cat, dtype: float64


count    892816.000000
mean          2.346606
std           0.831666
min          -1.000000
25%           2.000000
50%           3.000000
75%           3.000000
max           3.000000
Name: ps_car_11, dtype: float64


count    892816.000000
mean          0.379957
std           0.058385
min           0.141421
25%           0.316228
50%           0.374166
75%           0.400000
max           1.264911
Name: ps_car_12, dtype: float64


count    892816.000000
mean          0.813637
std           0.224779
min           0.275778
25%           0.671234
50%           0.766081
75%           0.906132
max           4.031301
Name: ps_car_13, dtype: float64


count    892816.000000
mean          0.276431
std           0.356835
min          -1.000000
25%           0.333916
50%           0.368782
75%           0.396485
max           0.636396
Name: ps_car_14, dtype: float64


count    892816.000000
mean          3.068325
std           0.729005
min           0.000000
25%           2.828427
50%           3.316625
75%           3.605551
max           3.741657
Name: ps_car_15, dtype: float64


count    892816.000000
mean          0.449632
std           0.287213
min           0.000000
25%           0.200000
50%           0.400000
75%           0.700000
max           0.900000
Name: ps_calc_01, dtype: float64

count    892816.000000
mean          0.450453
std           0.287373
min           0.000000
25%           0.200000
50%           0.500000
75%           0.700000
max           0.900000
Name: ps_calc_02, dtype: float64


count    892816.000000
mean          0.450054
std           0.287254
min           0.000000
25%           0.200000
50%           0.400000
75%           0.700000
max           0.900000
Name: ps_calc_03, dtype: float64


count    892816.000000
mean          2.371390
std           1.116953
min           0.000000
25%           2.000000
50%           2.000000
75%           3.000000
max           5.000000
Name: ps_calc_04, dtype: float64


count    892816.000000
mean          1.885328
std           1.136763
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           6.000000
Name: ps_calc_05, dtype: float64


count    892816.000000
mean          7.687805
std           1.333521
min           1.000000
25%           7.000000
50%           8.000000
75%           9.000000
max          10.000000
Name: ps_calc_06, dtype: float64


count    892816.000000
mean          3.009537
std           1.415155
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           9.000000
Name: ps_calc_07, dtype: float64


count    892816.000000
mean          9.225854
std           1.460560
min           1.000000
25%           8.000000
50%           9.000000
75%          10.000000
max          12.000000
Name: ps_calc_08, dtype: float64


count    892816.000000
mean          2.338538
std           1.248601
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           7.000000
Name: ps_calc_09, dtype: float64


count    892816.000000
mean          8.443167
std           2.906361
min           0.000000
25%           6.000000
50%           8.000000
75%          10.000000
max          25.000000
Name: ps_calc_10, dtype: float64


count    892816.000000
mean          5.438478
std           2.330081
min           0.000000
25%           4.000000
50%           5.000000
75%           7.000000
max          20.000000
Name: ps_calc_11, dtype: float64


count    892816.000000
mean          1.440265
std           1.200620
min           0.000000
25%           1.000000
50%           1.000000
75%           2.000000
max          11.000000
Name: ps_calc_12, dtype: float64


count    892816.000000
mean          2.875013
std           1.694072
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max          15.000000
Name: ps_calc_13, dtype: float64


count    892816.000000
mean          7.540367
std           2.745882
min           0.000000
25%           6.000000
50%           7.000000
75%           9.000000
max          28.000000
Name: ps_calc_14, dtype: float64


count    892816.000000
mean          0.123720
std           0.329262
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_calc_15_bin, dtype: float64


count    892816.000000
mean          0.627756
std           0.483403
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_calc_16_bin, dtype: float64


count    892816.000000
mean          0.554660
std           0.497004
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: ps_calc_17_bin, dtype: float64


count    892816.000000
mean          0.287796
std           0.452736
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_calc_18_bin, dtype: float64


count    892816.000000
mean          0.349344
std           0.476763
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: ps_calc_19_bin, dtype: float64


count    892816.000000
mean          0.152428
std           0.359435
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: ps_calc_20_bin, dtype: float64

In [18]:
test.describe()

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,8.928160e+05,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,...,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000
mean,7.441535e+05,1.902371,1.358613,4.413734,0.417361,0.408132,0.393246,0.257191,0.163659,0.185905,...,5.438478,1.440265,2.875013,7.540367,0.123720,0.627756,0.554660,0.287796,0.349344,0.152428
std,4.296830e+05,1.986503,0.663002,2.700149,0.493453,1.355068,0.488471,0.437086,0.369966,0.389030,...,2.330081,1.200620,1.694072,2.745882,0.329262,0.483403,0.497004,0.452736,0.476763,0.359435
min,0.000000e+00,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.720218e+05,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.443070e+05,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,1.116308e+06,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.488026e+06,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,1.000000,...,20.000000,11.000000,15.000000,28.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [19]:
sum = 0

In [20]:
for att in test:
    for val in test[att]:
        if val < 0:
            sum += 1

In [21]:
sum

1270295

In [5]:
%matplotlib

Using matplotlib backend: Qt5Agg

In [64]:
ps_ind_05_cat = train['ps_ind_05_cat'].hist(bins = 8)
ps_ind_05_cat.set_title('ps_ind_05_cat')